#include "Zombie.hpp"
//The parameter name represents the initial name assigned to each zombie created in the horde.
//"new" allocates memory on the heap and constructs object(s) in that memory

//->for single object:
//Type* ptr = new Type(constrictor_arguments)

//->for the array of objects
//Type *ptr = new Type[number_of_objects]

// Zombie* z = new Zombie(name);
// 	What happens exactly
// 1 Heap memory for N Zombies is allocated in one block
// 2️ The "default constructor" is called N times
// 3️ The address of the first Zombie is returned
// 4️ Stored in pointer horde

//What is the "DEFAULT constructor": A constructor that can be called with NO arguments. It has nothing to do (by itself) with whether it is written by you or generated by the compiler

Zombie* zombieHorde(int N, std::string name)
{
	Zombie* horde = new Zombie[N];
	for(int i = 0; i < N; i++)
	{
		horde[i].setName(name);
	}
	return horde;
}